# action.yml
name: openai-code-review
description: 'Integration of github actions with ChatGPT, aiming automated code reviews'
inputs:
  openai_api_key:
    description: 'OpenAI key'
    required: true
    default: ''
  github_token:
    description: 'Github token'
    required: true
    default: ''
  github_pr_id:
    description: 'Github PR ID'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_id }}
